module.exports = {
    "% free testosterone": "Testosterone, free",
    "absolute basophils": "Basophil",
    "absolute eosinophils": "Eosinophil",
    "absolute lymphocytes": "Lymphocyte",
    "absolute monocytes": "Monocyte",
    "absolute neutrophils": "Neutrophil",
    "albumin": "Albumin (Serum)",
    "albumin/globulin ratio": "Albumin/Globulin ratio",
    "alkaline phosphatase": "Alkaline Phosphatase",
    "alt": "ALT (SGPT)",
    "alt (sgpt)": "ALT (SGPT)",
    "apolipoprotein b": "ApoB",
    "arachidonic acid": "Arachidonic Acid",
    "arachidonic acid/epa ratio": "EPA/Arachidonic acid ratio",
    "ast": "AST (SGOT)",
    "ast (sgot)": "AST (SGOT)",
    "baso (absolute)": "Basophil",
    "basophils": "% Basophil",
    "basos": "% Basophil",
    "bilirubin, total": "Total Bilirubin",
    "bun": "BUN",
    "bun/creatinine ratio": "BUN/Creatinine ratio",
    "c-reactive protein, cardiac": "hs-CRP",
    "calcium": "Calcium (Serum)",
    "carbon dioxide": "Carbon Dioxide",
    "carbon dioxide, total": "Carbon Dioxide",
    "chloride": "Chloride",
    "chol/hdl c": "Cholesterol/HDL Ratio",
    "cholesterol, total": "Total Cholesterol",
    "cortisol": "Cortisol",
    "cortisol - am": "Cortisol",
    "cortisol, a.m.": "Cortisol",
    "creatinine": "Creatinine",
    "dha": "DHA",
    "dhea sulfate": "DHEA Sulfate",
    "dhea-sulfate": "DHEA Sulfate",
    "dpa": "DPA",
    "egfr": "eGFR",
    "eos": "% Eosinophil",
    "eos (absolute)": "Eosinophil",
    "eosinophils": "% Eosinophil",
    "epa": "EPA",
    "estradiol": "E2",
    "ferritin": "Ferritin (Serum)",
    "folate (folic acid), serum": "Folate",
    "free testosterone (direct)": "Testosterone, free",
    "fsh": "FSH",
    "ggt": "GGT",
    "globulin": "Globulin",
    "globulin, total": "Globulin",
    "globulin,total": "Globulin",
    "glucose": "Glucose",
    "hdl cholesterol": "HDL",
    "hdl-c": "HDL",
    "hdl-p (total)": "HDL-P",
    "hematocrit": "Hematocrit",
    "hemoglobin": "Hemoglobin",
    "hemoglobin a1c": "HbA1c",
    "homocyst(e)ine": "Homocysteine",
    "homocysteine": "Homocysteine",
    "insulin": "Insulin",
    "iron": "Iron",
    "iron bind.cap.(tibc)": "TIBC",
    "ldl chol calc (nih)": "LDL",
    "ldl cholesterol (calc)": "LDL",
    "ldl particle number": "LDL-P",
    "ldl size": "LDL Peak Size",
    "ldl-c (nih calc)": "LDL",
    "ldl-p": "LDL-P",
    "lh": "LH",
    "lymphocytes": "% Lymphocyte",
    "lymphs": "% Lymphocyte",
    "lymphs (absolute)": "Lymphocyte",
    "mch": "MCH",
    "mchc": "MCHC",
    "mcv": "MCV",
    "monocytes": "% Monocyte",
    "monocytes(absolute)": "Monocyte",
    "mpv": "MPV",
    "MPV":"MPV",
    "neutrophils": "% Neutrophil",
    "neutrophils (absolute)": "Neutrophil",
    "omega-3 total": "Omega 3 Index",
    "omega 3 total": "Omega 3 Index",
    "omega-6/omega-3 ratio": "Omega 6/Omega 3 ratio",
    "Omega 6 Total":"Omega 6 Total",
    "platelet count": "Platelet",
    "platelets": "Platelet",
    "potassium": "Potassium",
    "progesterone": "Progesterone",
    "prolactin": "Prolactin",
    "protein, total": "Total Protein",
    "protein,total": "Total Protein",
    "rbc": "RBC",
    "rdw": "RDW",
    "red blood cell count": "RBC",
    "reverse t3, serum": "Reverse T3",
    "sex hormone binding globulin": "SHBG",
    "small ldl-p": "Small LDL-P",
    "sodium": "Sodium",
    "t3, free": "Free T3",
    "t3,free": "Free T3",
    "t4, free (direct)": "Free T4 (Direct)",
    "t4, free(direct)": "Free T4 (Direct)",
    "t4,free (direct)": "Free T4 (Direct)",
    "t4,free(direct)": "Free T4 (Direct)",
    "testosterone": "Testosterone, total",
    "testosterone, bioavailable": "Testosterone, free",
    "testosterone, free": "Testosterone, free",
    "testosterone, total": "Testosterone, total",
    "testosterone,free": "Testosterone, free",
    "testosterone,total": "Testosterone, total",
    "thyroglobulin antibodies": "TGB Ab",
    "thyroglobulin antibody": "TGB Ab",
    "thyroid peroxidase (tpo) ab": "TPO Ab",
    "thyroid peroxidase antibodies": "TPO Ab",
    "thyroxine (t4)": "Total T4",
    "triglycerides": "Triglycerides",
    "triiodothyronine (t3)": "Total T3",
    "triiodothyronine (t3), free": "Free T3",
    "triiodothyronine (t3),free": "Free T3",
    "tsh": "TSH",
    "uibc": "UIBC",
    "urea nitrogen (bun)": "BUN",
    "uric acid": "Uric acid",
    "Uric acid":"Uric acid",
    "vitamin b12": "Vitamin B12",
    "vitamin d, 25-hydroxy": "Vitamin D (25-Hydroxy)",
    "vitamin d, 25-oh": "Vitamin D (25-Hydroxy)",
    "vldl cholesterol cal": "VLDL",
    "wbc": "WBC",
    "white blood cell count": "WBC",
    "% basophil": "% Basophil",
    "% eosinophil": "% Eosinophil",
    "% lymphocyte": "% Lymphocyte",
    "% monocyte": "% Monocyte",
    "% neutrophil": "% Neutrophil",
    "albumin (serum/plasma)": "Albumin (Serum)",
    "albumin-/globulin ratio (a/g)": "Albumin/Globulin ratio",
    "albumin/creatinine ratio (acr)": "Urine Albumin/Creatinine ratio",
    "alkaline phosphatase (alp)": "Alkaline Phosphatase",
    "alt (alanine aminotransferase/transaminase, sgpt)": "ALT (SGPT)",
    "anion gap": "Anion Gap",
    "apolipoprotein a (apoa)": "ApoA",
    "apolipoprotein b (apob)": "ApoB",
    "arsenic (blood, serum)": "Arsenic (Serum)",
    "ast (aspartate aminotransferase/transaminase, sgot)": "AST (SGOT)",
    "basophil absolute count": "Basophil",
    "bilirubin": "Total Bilirubin",
    "blood urea nitrogen (bun)": "BUN",
    "c-reactive protein (hs-crp)": "hs-CRP",
    "cadmium (blood, serum)": "Cadmium (Serum)",
    "calcium (serum)": "Calcium (Serum)",
    "carbon dioxide (co2, bicarbonate)": "Carbon Dioxide",
    "ceruloplasmin": "Ceruloplasmin",
    "cholesterol": "Total Cholesterol",
    "creatinine (serum/plasma)": "Creatinine",
    "dhea sulfate (dheas)": "DHEA Sulfate",
    "egfr (if african american/black)": "eGFR (African American/Black)",
    "egfr (if non-african american/black)": "eGFR",
    "eosinophil absolute count": "Eosinophil",
    "estimated average glucose (eag)": "eAG (Glucose)",
    "ferritin (iron, serum)": "Ferritin (Serum)",
    "folate (folic acid, vitamin b9)": "Folate",
    "free t3": "Free T3",
    "free t4 (direct) (free thyroxine index,t7)": "Free T4 (Direct)",
    "gamma-glutamyl transpeptidase (ggt)": "GGT",
    "glutathione": "Glutathione",
    "hdl-p (high-density lipoprotein particles)": "HDL-P",
    "hemoglobin a1c (hba1c)": "HbA1c",
    "homocysteine (homocyst(e)ine)": "Homocysteine",
    "igf-1 (insulin-like growth factor 1)": "IGF-1",
    "iodine (blood, serum, plasma)": "Iodine (Serum)",
    "ldl cholesterol (ldl, ldl-c)": "LDL",
    "ldl-p (low-density lipoprotein particles)": "LDL-P",
    "lead (blood, serum)": "Lead (Serum)",
    "lymphocyte absolute count": "Lymphocyte",
    "magnesium": "Magnesium",
    "mercury (blood, serum)": "Mercury (Serum)",
    "monocyte absolute count": "Monocyte",
    "mean platelet volume (mpv)": "MPV",
    "neutrophil absolute count": "Neutrophil",
    "phosphorus": "Phosphorus",
    "protein (total protein)": "Total Protein",
    "red blood count (rbc)": "RBC",
    "reverse t3": "Reverse T3",
    "t3 uptake": "T3 Uptake",
    "thyroglobulin antibody (tgb ab)": "TGB Ab",
    "thyroid-stimulating hormone (tsh)": "TSH",
    "tibc (total iron binding capacity)": "TIBC",
    "total cholesterol / hdl ratio": "Cholesterol/HDL Ratio",
    "total t3 (triiodothyronine)": "Total T3",
    "total t4 (thyroxine)": "Total T4",
    "uibc (unsaturated iron binding capacity)": "UIBC",
    "vitamin b6 (pyridoxine, pyridoxal 5-phosphate)": "Vitamin B6",
    "vitamin d, total 25-hydroxy": "Vitamin D (25-Hydroxy)",
    "vldl cholesterol": "VLDL",
    "white blood count (wbc)": "WBC",
    "zinc, rbc": "Zinc, RBC",
    "% eos": "% Eosinophil",
    "% lymphocytes": "% Lymphocyte",
    "% monos": "% Monocyte",
    "% neutrophils": "% Neutrophil",
    "ag": "Anion Gap",
    "alb/creat ratio": "Urine Albumin/Creatinine ratio",
    "apoa": "ApoA",
    "apob": "ApoB",
    "arsenic, blood": "Arsenic (Serum)",
    "basophil abs count": "Basophil",
    "% basophils": "% Basophil",
    "blood lead": "Lead (Serum)",
    "bun / creatinine ratio": "BUN/Creatinine ratio",
    "cadmium, blood": "Cadmium (Serum)",
    "cholesterol to hdl ratio": "Cholesterol/HDL Ratio",
    "egfr if africn am": "eGFR (African American/Black)",
    "egfr if nonafricn am": "eGFR",
    "eosinophil absolute ct": "Eosinophil",
    "estim. avg glu (eag)": "eAG (Glucose)",
    "folate": "Folate",
    "ft3": "Free T3",
    "ft4": "Free T4 (Direct)",
    "hdl": "HDL",
    "hdls": "HDL-P",
    "hg": "Mercury (Serum)",
    "hs crp": "hs-CRP",
    "insulin-like growth factor 1": "IGF-1",
    "iodine, serum or plasma": "Iodine (Serum)",
    "ldl": "LDL",
    "ldlp": "LDL-P",
    "lymphocyte abs cnt": "Lymphocyte",
    "monocyte abs count": "Monocyte",
    "ph": "Phosphorus",
    "rt3": "Reverse T3",
    "sd-ldl": "Small LDL-P",
    "thyroid peroxidase(tpo) ab": "TPO Ab",
    "total bilirubin": "Total Bilirubin",
    "total cholesterol": "Total Cholesterol",
    "total glutathione": "Glutathione",
    "total protein": "Total Protein",
    "tt3": "Total T3",
    "tt4": "Total T4",
    "vb6": "Vitamin B6",
    "vitamin d 25-dihydroxy": "Vitamin D (25-Hydroxy)",
    "vldl": "VLDL",
    "dha (88995-6)": "DHA",
    "zinc,rbc": "Zinc, RBC",
    "% monocytes": "% Monocyte",
    "25ohd": "Vitamin D (25-Hydroxy)",
    "a/g ratio": "Albumin/Globulin ratio",
    "a1c": "HbA1c",
    "alanine transaminase": "ALT (SGPT)",
    "apo-a": "ApoA",
    "apo-b": "ApoB",
    "arsenic,blood": "Arsenic (Serum)",
    "aspartate transaminase": "AST (SGOT)",
    "average glucose": "eAG (Glucose)",
    "bilirubin total": "Total Bilirubin",
    "bll": "Lead (Serum)",
    "bun/creat ratio": "BUN/Creatinine ratio",
    "cadmium,blood": "Cadmium (Serum)",
    "ceru": "Ceruloplasmin",
    "chol hdl ratio": "Cholesterol/HDL Ratio",
    "cholesterol total": "Total Cholesterol",
    "co2 (bicarbonate)": "Carbon Dioxide",
    "cpr": "CRP",
    "creat": "Creatinine",
    "dheas": "DHEA Sulfate",
    "egfr if african amer": "eGFR (African American/Black)",
    "egfr if non-african american": "eGFR",
    "eosinophil %": "% Eosinophil",
    "eosinophil abs ct": "Eosinophil",
    "fn": "Ferritin (Serum)",
    "gamma-glutamyl transpeptidase": "GGT",
    "glb": "Globulin",
    "glc": "Glucose",
    "gsh": "Glutathione",
    "haemoglobin": "Hemoglobin",
    "hdlp": "HDL-P",
    "ionized calcium": "Calcium (Serum)",
    "ldl chol calc": "LDL",
    "mean corpuscular hemoglobin": "MCH",
    "mean corpuscular hemoglobin concentration": "MCHC",
    "mean corpuscular volume": "MCV",
    "mean platelet volume": "MPV",
    "mercury, blood": "Mercury (Serum)",
    "mg": "Magnesium",
    "microalbumin creatinine ratio": "Urine Albumin/Creatinine ratio",
    "monocytes (absolute)": "Monocyte",
    "na": "Sodium",
    "packed cell volume": "Hematocrit",
    "po4": "Phosphorus",
    "rbc, rdw": "RDW",
    "reverse t3,serum": "Reverse T3",
    "salkaline phosphatase": "Alkaline Phosphatase",
    "sdldl": "Small LDL-P",
    "serum albumin": "Albumin (Serum)",
    "serum anion gap": "Anion Gap",
    "serum bun": "BUN",
    "serum chloride": "Chloride",
    "serum potassium": "Potassium",
    "serum protein": "Total Protein",
    "somatomedin c": "IGF-1",
    "t3u": "T3 Uptake",
    "t4, free": "Free T4 (Direct)",
    "thyroid peroxidase ab": "TPO Ab",
    "tith": "Total T3",
    "triglyceride": "Triglycerides",
    "vb12": "Vitamin B12",
    "vb9": "Folate",
    "wbc count": "WBC",
    "25-ohd": "Vitamin D (25-Hydroxy)",
    "abs. basophil": "Basophil",
    "abs. lymphocyte": "Lymphocyte",
    "abs. monocyte": "Monocyte",
    "abs. neutrophil": "Neutrophil",
    "acr": "Urine Albumin/Creatinine ratio",
    "eag": "eAG (Glucose)",
    "alanine aminotransferase": "ALT (SGPT)",
    "alb": "Albumin (Serum)",
    "albumin/globulin": "Albumin/Globulin ratio",
    "alp": "Alkaline Phosphatase",
    "apb": "ApoB",
    "apoa1": "ApoA",
    "b.u.n.": "BUN",
    "basophil": "% Basophil",
    "bili": "Total Bilirubin",
    "bun/creat": "BUN/Creatinine ratio",
    "c-reactive protein,cardiac": "hs-CRP",
    "cl": "Chloride",
    "co2": "Carbon Dioxide",
    "crl": "Ceruloplasmin",
    "eosinophils %": "% Eosinophil",
    "fe": "Ferritin (Serum)",
    "folate (folic acid),serum": "Folate",
    "gfr est-african american": "eGFR (African American/Black)",
    "gfr est-other": "eGFR",
    "ggtp": "GGT",
    "glucose, random": "Glucose",
    "gt": "Glutathione",
    "hct": "Hematocrit",
    "hdl-p": "HDL-P",
    "hgb": "Hemoglobin",
    "hgba1c": "HbA1c",
    "high density lipoprotein": "HDL",
    "ldl chol. (direct)": "LDL",
    "lead, blood (adult)": "Lead (Serum)",
    "lymphocyte": "% Lymphocyte",
    "mag": "Magnesium",
    "mercury,blood": "Mercury (Serum)",
    "neutrophil": "% Neutrophil",
    "php": "Phosphorus",
    "platelets count": "Platelet",
    "potassium, serum": "Potassium",
    "protein, total, serum / plasma": "Total Protein",
    "rbc count": "RBC",
    "red cell distribution width": "RDW",
    "serum creatinine": "Creatinine",
    "serum glutamic-oxaloacetic transaminase (sgot)": "AST (SGOT)",
    "sldl-p": "Small LDL-P",
    "sodium, serum / plasma": "Sodium",
    "t. chol/hdl ratio": "Cholesterol/HDL Ratio",
    "t3, reverse": "Reverse T3",
    "tg": "Triglycerides",
    "thyroglobulin auto": "TGB Ab",
    "thyroid perox autoab": "TPO Ab",
    "total calcium": "Calcium (Serum)",
    "trit": "Total T3",
    "vldl (calculated)": "VLDL",
    "abs. eosinophil": "Eosinophil",
    "abtga": "TGB Ab",
    "alat": "ALT (SGPT)",
    "albumin, serum / plasma": "Albumin (Serum)",
    "alkpase": "Alkaline Phosphatase",
    "apo-a1": "ApoA",
    "basophil abs": "Basophil",
    "basophils %": "% Basophil",
    "bun to creatanine": "BUN/Creatinine ratio",
    "c-reactive protein,ser,ql": "hs-CRP",
    "calcium, serum": "Calcium (Serum)",
    "chloride, serum / plasma": "Chloride",
    "cholesterol,total": "Total Cholesterol",
    "cholesterol/hdl ratio": "Cholesterol/HDL Ratio",
    "crit": "Hematocrit",
    "crtn": "Creatinine",
    "egfr african american": "eGFR (African American/Black)",
    "egfr non afr american": "eGFR",
    "eos %": "% Eosinophil",
    "erythrocyte distribution width": "RDW",
    "fer": "Ferritin (Serum)",
    "folate, serum": "Folate",
    "glucose, blood glucose": "Glucose",
    "gth": "Glutathione",
    "gtp": "GGT",
    "ha1c": "HbA1c",
    "hb": "Hemoglobin",
    "ldl calculated": "LDL",
    "lead,blood": "Lead (Serum)",
    "lymphocyte abs": "Lymphocyte",
    "lymphocytes %": "% Lymphocyte",
    "monocyte abs": "Monocyte",
    "monos %": "% Monocyte",
    "neutrophil abs": "Neutrophil",
    "neutrophils %": "% Neutrophil",
    "plasma total homocysteine": "Homocysteine",
    "plt": "Platelet",
    "red blood cells count": "RBC",
    "serum, potassium": "Potassium",
    "sgot": "AST (SGOT)",
    "sodium, serum": "Sodium",
    "total co2": "Carbon Dioxide",
    "tpoa": "TPO Ab",
    "trig": "Triglycerides",
    "urea nitrogen, serum / plasma": "BUN",
    "very low-density cholesterol": "VLDL",
    "vitamin d,25-hydroxy": "Vitamin D (25-Hydroxy)",
    "% baso": "% Basophil",
    "% lymph": "% Lymphocyte",
    "% mono": "% Monocyte",
    "% neut": "% Neutrophil",
    "albumin, serum": "Albumin (Serum)",
    "alph": "Alkaline Phosphatase",
    "asat": "AST (SGOT)",
    "baso": "Basophil",
    "calcium, total, serum / plasma": "Calcium (Serum)",
    "chloride, serum": "Chloride",
    "chol/hdl": "Cholesterol/HDL Ratio",
    "creatinine, serum / plasma": "Creatinine",
    "crp, highly sensitive": "hs-CRP",
    "eosinophil abs": "Eosinophil",
    "eosinophils, %": "% Eosinophil",
    "erythrocyte count": "RBC",
    "ftn": "Ferritin (Serum)",
    "gamma-gt": "GGT",
    "glomerular filtration rate": "eGFR",
    "glucose, serum": "Glucose",
    "good cholesterol": "HDL",
    "gpt": "ALT (SGPT)",
    "hgb a1c": "HbA1c",
    "ldl cholesterol": "LDL",
    "llymph": "% Lymphocyte",
    "mono": "% Monocyte",
    "neutrophil auto count": "Neutrophil",
    "pcv": "Hematocrit",
    "plt count": "Platelet",
    "protein, total, serum": "Total Protein",
    "tco2": "Carbon Dioxide",
    "tgab": "TGB Ab",
    "tpx": "TPO Ab",
    "triglycerides, serum": "Triglycerides",
    "urea nitrogen,blood (bun)": "BUN",
    "very low-density lipoprotein": "VLDL",
    "vitamin d,25-oh,total,ia": "Vitamin D (25-Hydroxy)",
    "white blood cell": "WBC",
    "% bas": "% Basophil",
    "% lym": "% Lymphocyte",
    "% mnc": "% Monocyte",
    "% nph": "% Neutrophil",
    "aat": "AST (SGOT)",
    "alk phos": "Alkaline Phosphatase",
    "carbon dioxide content": "Carbon Dioxide",
    "cholesterol ratio": "Cholesterol/HDL Ratio",
    "creatinine, serum": "Creatinine",
    "ferritin, serum": "Ferritin (Serum)",
    "gamma-gtp": "GGT",
    "gfr": "eGFR",
    "hga1c": "HbA1c",
    "ldl-cholesterol": "LDL",
    "leukocyte count": "WBC",
    "neut": "Neutrophil",
    "sgpt": "ALT (SGPT)",
    "tg-ab": "TGB Ab",
    "urea nitrogen, bun": "BUN",
    "vitd,25-hydroxy tot": "Vitamin D (25-Hydroxy)",
    "vldl (calc)": "VLDL",
    "1,25-dihydroxy": "Vitamin D (25-Hydroxy)",
    "asp-t": "AST (SGOT)",
    "bas": "Basophil",
    "bas %": "% Basophil",
    "co2 content": "Carbon Dioxide",
    "gamma-gtase": "GGT",
    "ldl cholesterol calc": "LDL",
    "lym": "Lymphocyte",
    "lym %": "% Lymphocyte",
    "mnc": "Monocyte",
    "mnc %": "% Monocyte",
    "nph": "Neutrophil",
    "nph %": "% Neutrophil",
    "total-cholesterol-to-hdl": "Cholesterol/HDL Ratio",
    "urea nitrogen, blood (bun)": "BUN",
    "1,25-dihydroxycholecalciferol": "Vitamin D (25-Hydroxy)",
    "basophils, %": "% Basophil",
    "bicarb": "Carbon Dioxide",
    "gamma-gtpase": "GGT",
    "got": "AST (SGOT)",
    "low-density lipoprotein cholesterol": "LDL",
    "lymp": "% Lymphocyte",
    "mc": "Monocyte",
    "monocytes, %": "% Monocyte",
    "neutro": "Neutrophil",
    "total lymphocytes, %": "% Lymphocyte",
    "total neutrophils, %": "% Neutrophil",
    "abc": "Basophil",
    "alc": "Lymphocyte",
    "amc": "Monocyte",
    "anc": "Neutrophil",
    "cholesterol, ldl": "LDL",
    "eosin": "Eosinophil",
    "hco3": "Carbon Dioxide",
    "aec": "Eosinophil",
    "basophils, absolute": "Basophil",
    "bicarbonate": "Carbon Dioxide",
    "lymphocytes, absolute": "Lymphocyte",
    "monocytes, absolute": "Monocyte",
    "neutrophils, absolute": "Neutrophil",
    "carbon dioxide,total": "Carbon Dioxide",
    "eosinophils, absolute": "Eosinophil",
    "follicle-stimulating hormone": "FSH",
    "follicle-stimulating hormone (fsh)": "FSH",
    "luteinizing hormone": "LH",
    "luteinizing hormone (lh)": "LH",
    "pg": "Progesterone",
    "progesterone/e2 ratio": "Progesterone/E2 ratio",
    "estradiol-to-progesterone": "Progesterone/E2 ratio",
    "pg/e2": "Progesterone/E2 ratio",
    "p/e2": "Progesterone/E2 ratio",
    "antinuclear antibody": "ANA Direct",
    "ana direct": "ANA Direct",
    "ana screen": "ANA Direct",
    "ana screen, ifa": "ANA Direct",
    "ana, ifa": "ANA Direct",
    "ana titer": "ANA Titer",
    "antinuclear antibody titer": "ANA Titer",
    "ana by ifa rfx titer/pattern": "ANA Titer",
    "lyme antibody": "Lyme antibody",
    "lyme total antibody cia": "Lyme antibody",
    "nuclear membrane pattern": "Nuclear Membrane Pattern",
    "rim pattern": "Nuclear Membrane Pattern",
    "peripheral pattern": "Nuclear Membrane Pattern",
    "rim (peripheral)": "Nuclear Membrane Pattern",
    "peripheral": "Nuclear Membrane Pattern",
    "nuclear membrane": "Nuclear Membrane Pattern",
    "microalbumin": "Microalbumin",
    "urine - albumin": "Urine Albumin",
    "urine albumin": "Urine Albumin",
    "urine creatinine": "Urine Creatinine",
    "urine - creatinine": "Urine Creatinine",
    "urine albumin/creatinine ratio": "Urine Albumin/Creatinine ratio",
    "urine protein/creatinine ratio": "Urine Protein/Creatinine ratio",
    "urine - ketones": "Urine Ketones",
    "urine ketones": "Urine Ketones",
    "urine appearance": "Urine Appearance",
    "urine - appearance": "Urine Appearance",
    "urine - color": "Urine Color",
    "urine color": "Urine Color",
    "urine bilirubin": "Urine Bilirubin",
    "urine - bilirubin": "Urine Bilirubin",
    "urobilinogen,semi-qn": "Urobilinogen,Semi-Qn",
    "urobilinogen, semi-qn": "Urobilinogen,Semi-Qn",
    "urine glucose": "Urine Glucose",
    "urine - glucose": "Urine Glucose",
    "urine - wbc": "Urine WBC",
    "urine - wbc esterase": "Urine WBC Esterase",
    "urine - nitrite": "Urine Nitrite",
    "urine - occult blood": "Urine Occult Blood",
    "urine - rbc": "Urine RBC",
    "urine - protein": "Urine Protein",
    "urine - epithelial cells (non renal)": "Urine Epithelial cells (non renal)",
    "urine - squamous epithelial cells": "Urine Squamous Epithelial cells",
    "urine - transitional epithelial cells": "Urine Transitional Epithelial cells",
    "urine - renal epithelial cells": "Urine Renal Epithelial cells",
    "urine - bacteria": "Urine Bacteria",
    "urine - hyaline casts": "Urine Hyaline Casts",
    "urine - casts": "Urine Casts",
    "urine - granular casts": "Urine Granular Casts",
    "urine - specific gravity": "Urine Specific Gravity",
    "urine - ph": "Urine pH",
    "urine cystatin c": "Urine Cystatin C",
    "c-peptide": "C-Peptide",
    "urine nitrite": "Urine Nitrite",
    "urine occult blood": "Urine Occult Blood",
    "urine rbc": "Urine RBC",
    "urine protein": "Urine Protein",
    "urine epithelial cells (non renal)": "Urine Epithelial cells (non renal)",
    "urine squamous epithelial cells": "Urine Squamous Epithelial cells",
    "urine transitional epithelial cells": "Urine Transitional Epithelial cells",
    "urine renal epithelial cells": "Urine Renal Epithelial cells",
    "urine bacteria": "Urine Bacteria",
    "urine hyaline casts": "Urine Hyaline Casts",
    "urine casts": "Urine Casts",
    "urine granular casts": "Urine Granular Casts",
    "urine specific gravity": "Urine Specific Gravity",
    "urine ph": "Urine pH",
    "antinuclear antibody pattern": "ANA Pattern",
    "ana homogenous pattern": "Homogenous Pattern",
    "ana speckled pattern": "Speckled Pattern",
    "ana nucleolar pattern": "Nucleolar Pattern",
    "ana centromere pattern": "Centromere Pattern",
    "ana nuclear dot pattern": "Nuclear Dot Pattern",
    "ana nuclear membrane pattern": "Nuclear Membrane Pattern",
    "ana peripheral pattern": "Peripheral Pattern",
    "rheumatoid factor": "RF",
    "adiponectin": "Adiponectin",
    "leptin": "Leptin",
    "clam (f207) ige": "Clam IGE",
    "crab (f23) ige": "Crab IGE",
    "lobster (f80) ige": "Lobster IGE",
    "scallop (f338) ige": "Scallop IGE",
    "shrimp (f24) ige": "Shrimp IGE",
    "codfish (f3) ige": "Codfish IGE",
    "salmon (f41) ige": "Salmon IGE",
    "tuna (f40) ige": "Tuna IGE",
    "wheat (f4) ige": "Wheat IGE",
    "soybean (f14) ige": "Soybean IGE",
    "sesame seed (f10) ige": "Sesame Seed IGE",
    "almond (f20) ige": "Almond IGE",
    "cashew nut (f202) ige": "Cashew Nut IGE",
    "peanut (f13) ige": "Peanut IGE",
    "walnut (f256) ige": "Walnut IGE",
    "hazelnut (f17) ige": "Hazelnut IGE",
    "egg white (f1) ige": "Egg White IGE",
    "cow's milk (f2) ige": "Cow's Milk IGE",
    "clam ige": "Clam IGE",
    "crab ige": "Crab IGE",
    "lobster ige": "Lobster IGE",
    "scallop ige": "Scallop IGE",
    "shrimp ige": "Shrimp IGE",
    "codfish ige": "Codfish IGE",
    "salmon ige": "Salmon IGE",
    "tuna ige": "Tuna IGE",
    "wheat ige": "Wheat IGE",
    "soybean ige": "Soybean IGE",
    "sesame seed ige": "Sesame Seed IGE",
    "almond ige": "Almond IGE",
    "cashew nut ige": "Cashew Nut IGE",
    "peanut ige": "Peanut IGE",
    "walnut ige": "Walnut IGE",
    "hazelnut ige": "Hazelnut IGE",
    "egg white ige": "Egg White IGE",
    "cow's milk ige": "Cow's Milk IGE",
    "amylase": "Amylase",
    "lipase": "Lipase",
    "crp": "CRP",
    "esr": "ESR",
    "prothrombin time (pt)": "PT",
    "activated partial thromboplastin time (aptt)": "aPTT",
    "prolonged ptt": "Prolonged PTT",
    "inr": "INR",
    "estradiol (estrogen fraction e2)": "E2",
    "estrone (e1)": "E1",
    "estrone": "E1",
    "hdl large": "HDL Large",
    "ldl medium": "LDL Medium",
    "ldl pattern": "LDL Pattern",
    "ldl small": "LDL Small",
    "estriol": "Estriol",
    "lipoprotein (a)": "Lipoprotein (A)",
    "mma": "MMA",
    "methylmalonic acid (mma)": "MMA",
    "methylmalonic acid": "MMA",
    "psa, total": "PSA, Total",
    "psa%, free": "PSA%, Free",
    "prostate-specific antigen (psa) %, free": "PSA%, Free",
    "prostate-specific antigen (psa), total": "PSA, Total",
    "copper (serum)": "Copper (Serum)",
    "apob-to-apoa ratio": "ApoB/ApoA Ratio",
    "apob/apoa ratio": "ApoB/ApoA Ratio",
    "albumin": "Albumin",
    "albumin (serum/plasma)": "Albumin",
    "calcium": "Calcium",
    "alkaline phosphatase": "Alkaline Phosphatase",
    "Alkaline Phosphatase":"Alkaline Phosphatase",
    "insulin (free/bioactive)": "Insulin",
    "ferritin (iron)": "Ferritin",
    "iron binding capacity": "TIBC",
    "% saturation": "% Saturation (Iron)",
    "fibrinogen": "Fibrinogen",
    "non-hdl cholesterol": "Non-HDL Cholesterol",
    "docosapentaenoic acid": "DPA",
    "tg/hdl-c ratio": "TG/HDL-C Ratio",
    "ldl size": "LDL Size",
    "ldl pattern": "LDL Pattern",
    "hdl size": "HDL Size",
    "linoleic acid": "Linoleic Acid",
     "Neutrophils (Absolute)": "Neutrophil (Absolute)",
  "Lymphs (Absolute)": "Lymphocyte (Absolute)",
  "Monocytes(Absolute)": "Monocyte (Absolute)",
  "Immature Grans (Abs)": "Immature Granulocytes (Absolute)",
      "Iron Saturation": "% Saturation (Iron)",
      "Magnesium, RBC": "Magnesium, RBC",
      "Sex Hormone Binding Glob, Serum": "SHBG",
      "Sedimentation Rate - Westergren": "ESR",
      "Thyroglobulin Antibody": "TGB Ab",
      "Immature Granulocytes": "Immature Granulocytes",
      "Immature Grans (Abs)": "Immature Grans (Abs)",
      "Reticulocyte Count": "Reticulocyte Count",
      "Ferritin (Iron)": "Ferritin",
      "Serum Ferritin": "Ferritin",
      "Ferritin Level": "Ferritin",  
      "ferritin": "Ferritin", 
    "ferritin 01": "Ferritin", 
    "sex horm binding glob, serum": "SHBG",
    "sex hormone binding glob, serum": "SHBG", 
  
}