module.exports = {
    "WBC": null,
    "RBC": null,
    "Hemoglobin": null,
    "Hematocrit": null,
    "MCV": null,
    "MCH": null,
    "MCHC": null,
    "RDW": null,
    "Platelet": null,
    "MPV": null,
    "Neutrophil": null,
    "Lymphocyte": null,
    "Monocyte": null,
    "Eosinophil": null,
    "Basophil": null,
    "% Neutrophil": null,
    "% Lymphocyte": null,
    "% Monocyte": null,
    "% Eosinophil": null,
    "% Basophil": null,
    "Total Cholesterol": null,
    "HDL": null,
    "Triglycerides": null,
    "LDL": null,
    "VLDL": null,
    "Cholesterol/HDL Ratio": null,
    "Glucose": null,
    "BUN": null,
    "Creatinine": null,
    "BUN/Creatinine ratio": null,
    "eGFR": null,
    "eGFR (African American/Black)": null,
    "Sodium": null,
    "Potassium": null,
    "Chloride": null,
    "Carbon Dioxide": null,
    "Calcium": null,
    "Total Protein": null,
    "Albumin": null,
    "Globulin": null,
    "Albumin/Globulin ratio": null,
    "Total Bilirubin": null,
    "Alkaline Phosphatase": null,
    "AST (SGOT)": null,
    "ALT (SGPT)": null,
    "GGT": null,
    "HbA1c": null,
    "eAG (Glucose)": null,
    "Phosphorus": null,
    "Magnesium": null,
    "Anion Gap": null,
    "hs-CRP": null,
    "Homocysteine": null,
    "Uric acid": null,
    "Amylase": null,
    "Lipase": null,
    "Insulin": null,
    "CRP": null,
    "Adiponectin": null,
    "Leptin": null,
    "ApoA": null,
    "ApoB": null,
    "LDL-P": null,
    "HDL-P": null,
    "Small LDL-P": null,
    "ApoB/ApoA Ratio": null,
    "Lipoprotein (A)": null,
    "LDL Peak Size": null,
    "LDL Small": null,
    "LDL Medium": null,
    "LDL Pattern": null,
    "HDL Large": null,
    "TSH": null,
    "Total T4": null,
    "Free T4 (Direct)": null,
    "Total T3": null,
    "Free T3": null,
    "Reverse T3": null,
    "T3 Uptake": null,
    "TGB Ab": null,
    "TPO Ab": null,
    "Ferritin": null,
    "Iron": null,
    "TIBC": null,
    "UIBC": null,
    "Vitamin D (25-Hydroxy)": null,
    "Vitamin B12": null,
    "Folate": null,
    "Vitamin B6": null,
    "Copper (Serum)": null,
    "Ceruloplasmin": null,
    "Zinc, RBC": null,
    "Iodine (Serum)": null,
    "MMA": null,
    "Glutathione": null,
    "DHEA Sulfate": null,
    "IGF-1": null,
    "FSH": null,
    "LH": null,
    "Progesterone": null,
    "Progesterone/E2 ratio": null,
    "Testosterone, free": null,
    "Testosterone, total": null,
    "E2": null,
    "E1": null,
    "Estriol": null,
    "Prolactin": null,
    "PSA%, Free": null,
    "PSA, Total": null,
    "SHBG": null,
    "Cortisol": null,
    "Lead (Serum)": null,
    "Arsenic (Serum)": null,
    "Mercury (Serum)": null,
    "Cadmium (Serum)": null,
    "ESR": null,
    "PT": null,
    "aPTT": null,
    "Prolonged PTT": null,
    "INR": null,
    "Omega 3 Index": null,
    "Omega 6/Omega 3 ratio": null,
    "EPA/Arachidonic acid ratio": null,
    "Arachidonic acid": null,
    "EPA": null,
    "DHA": null,
    "ANA Direct": null,
    "ANA Titer": null,
    "ANA Pattern": null,
    "Homogenous Pattern": null,
    "Speckled Pattern": null,
    "Nucleolar Pattern": null,
    "Centromere Pattern": null,
    "Nuclear Dot Pattern": null,
    "Nuclear Membrane Pattern": null,
    "Peripheral Pattern": null,
    "RF": null,
    "Lyme antibody": null,
    "Clam IGE": null,
    "Crab IGE": null,
    "Lobster IGE": null,
    "Scallop IGE": null,
    "Shrimp IGE": null,
    "Codfish IGE": null,
    "Salmon IGE": null,
    "Tuna IGE": null,
    "Wheat IGE": null,
    "Soybean IGE": null,
    "Sesame Seed IGE": null,
    "Almond IGE": null,
    "Cashew Nut IGE": null,
    "Peanut IGE": null,
    "Walnut IGE": null,
    "Hazelnut IGE": null,
    "Egg White IGE": null,
    "Cow s Milk IGE": null,
    "Microalbumin": null,
    "Urine Albumin": null,
    "Urine Creatinine": null,
    "Urine Albumin/Creatinine ratio": null,
    "Urine Protein/Creatinine ratio": null,
    "Urine Ketones": null,
    "Urine Appearance": null,
    "Urine Color": null,
    "Urine Bilirubin": null,
    "Urobilinogen,Semi-Qn": null,
    "Urine Glucose": null,
    "Urine WBC": null,
    "Urine WBC Esterase": null,
    "Urine Nitrite": null,
    "Urine Occult Blood": null,
    "Urine RBC": null,
    "Urine Protein": null,
    "Urine Epithelial cells (non renal)": null,
    "Urine Squamous Epithelial cells": null,
    "Urine Transitional Epithelial cells": null,
    "Urine Renal Epithelial cells": null,
    "Urine Bacteria": null,
    "Urine Hyaline Casts": null,
    "Urine Casts": null,
    "Urine Granular Casts": null,
    "Urine Specific Gravity": null,
    "Urine pH": null,
    "Urine Cystatin C": null,
    "C-Peptide": null,
    "Albumin (Serum/Plasma)": null,
    "blood Glucose": null,
    "AST (Aspartate aminotransferase/transaminase, SGOT)": null,
    "Gamma-glutamyl transpeptidase (GGT)": null,
    "Ferritin (Iron)": null,
    "% Saturation (Iron)": null,
    "Fibrinogen": null,
    "Non-HDL Cholesterol": null,
    "DPA": null,
    "TG/HDL-C Ratio": null,
    "LDL Size": null,
    "LDL Pattern": null,
    "HDL Size": null,
    "Linoleic Acid": null
};